[build]
  command="ng build"
  publish="dist/angular-quickstart"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  [plugins.inputs.postBuild]
    enable = false

  [plugins.inputs]
    enable = false
